export const COUNTRIES = [
  { name: "UNITED STATES", iso3: "USA" },
  { name: "CANADA", iso3: "CAN" },
  { name: "AFGHANISTAN", iso3: "AFG" },
  { name: "ALBANIA", iso3: "ALB" },
  { name: "ALGERIA", iso3: "DZA" },
  { name: "AMERICAN SAMOA", iso3: "ASM" },
  { name: "ANDORRA", iso3: "AND" },
  { name: "ANGOLA", iso3: "AGO" },
  { name: "ANGUILLA", iso3: "AIA" },
  { name: "ANTIGUA AND BARBUDA", iso3: "ATG" },
  { name: "ARGENTINA", iso3: "ARG" },
  { name: "ARMENIA", iso3: "ARM" },
  { name: "ARUBA", iso3: "ABW" },
  { name: "AUSTRALIA", iso3: "AUS" },
  { name: "AUSTRIA", iso3: "AUT" },
  { name: "AZERBAIJAN", iso3: "AZE" },
  { name: "BAHRAIN", iso3: "BHR" },
  { name: "BAKER ISLAND", iso3: "XBK" },
  { name: "BANGLADESH", iso3: "BGD" },
  { name: "BARBADOS", iso3: "BRB" },
  { name: "BELARUS", iso3: "BLR" },
  { name: "BELGIUM", iso3: "BEL" },
  { name: "BELIZE", iso3: "BLZ" },
  { name: "BENIN", iso3: "BEN" },
  { name: "BERMUDA", iso3: "BMU" },
  { name: "BHUTAN", iso3: "BTN" },
  { name: "BOLIVIA", iso3: "BOL" },
  { name: "BONAIRE", iso3: "BON" },
  { name: "BOSNIA AND HERZEGOVINA", iso3: "BIH" },
  { name: "BOTSWANA", iso3: "BWA" },
  { name: "BRAZIL", iso3: "BRA" },
  { name: "BRITISH VIRGIN ISLANDS", iso3: "VGB" },
  { name: "BRUNEI", iso3: "BRN" },
  { name: "BULGARIA", iso3: "BGR" },
  { name: "BURKINA FASO", iso3: "BFA" },
  { name: "BURMA", iso3: "MMR" },
  { name: "BURUNDI", iso3: "BDI" },
  { name: "CAMBODIA", iso3: "KHM" },
  { name: "CAMEROON", iso3: "CMR" },
  { name: "CABO VERDE", iso3: "CPV" },
  { name: "CAYMAN ISLANDS", iso3: "CYM" },
  { name: "CENTRAL AFRICAN REPUBLIC", iso3: "CAF" },
  { name: "CHAD", iso3: "TCD" },
  { name: "CHILE", iso3: "CHL" },
  { name: "CHINA", iso3: "CHN" },
  { name: "CHRISTMAS ISLAND", iso3: "CXR" },
  { name: "COCOS ISLANDS", iso3: "CCK" },
  { name: "COLOMBIA", iso3: "COL" },
  { name: "COMOROS", iso3: "COM" },
  { name: "CONGO-BRAZZAVILLE", iso3: "COG" },
  { name: "CONGO-KINSHASA", iso3: "COD" },
  { name: "COOK ISLANDS", iso3: "COK" },
  { name: "COSTA RICA", iso3: "CRI" },
  { name: "CROATIA", iso3: "HRV" },
  { name: "CUBA", iso3: "CUB" },
  { name: "CURACAO", iso3: "CUR" },
  { name: "CYPRUS", iso3: "CYP" },
  { name: "CZECH REPUBLIC", iso3: "CZE" },
  { name: "DENMARK", iso3: "DNK" },
  { name: "DJIBOUTI", iso3: "DJI" },
  { name: "DOMINICA", iso3: "DMA" },
  { name: "DOMINICAN REPUBLIC", iso3: "DOM" },
  { name: "ECUADOR", iso3: "ECU" },
  { name: "EGYPT", iso3: "EGY" },
  { name: "EL SALVADOR", iso3: "SLV" },
  { name: "EQUATORIAL GUINEA", iso3: "GNQ" },
  { name: "ERITREA", iso3: "ERI" },
  { name: "ESTONIA", iso3: "EST" },
  { name: "ESWATINI", iso3: "SWZ" },
  { name: "ETHIOPIA", iso3: "ETH" },
  { name: "FALKLAND ISLANDS", iso3: "FLK" },
  { name: "FAROE ISLANDS", iso3: "FRO" },
  { name: "FIJI", iso3: "FJI" },
  { name: "FINLAND", iso3: "FIN" },
  { name: "FRANCE", iso3: "FRA" },
  { name: "FRENCH GUIANA", iso3: "GUF" },
  { name: "FRENCH POLYNESIA", iso3: "PYF" },
  { name: "GABON", iso3: "GAB" },
  { name: "GAZA STRIP", iso3: "XGZ" },
  { name: "GEORGIA", iso3: "GEO" },
  { name: "GERMANY", iso3: "DEU" },
  { name: "GHANA", iso3: "GHA" },
  { name: "GIBRALTAR", iso3: "GIB" },
  { name: "GREECE", iso3: "GRC" },
  { name: "GREENLAND", iso3: "GRL" },
  { name: "GRENADA", iso3: "GRD" },
  { name: "GUADELOUPE", iso3: "GLP" },
  { name: "GUAM, U.S.A.", iso3: "GUM" },
  { name: "GUATEMALA", iso3: "GTM" },
  { name: "GUERNSEY", iso3: "GGY" },
  { name: "GUINEA", iso3: "GIN" },
  { name: "GUINEA-BISSAU", iso3: "GNB" },
  { name: "GUYANA", iso3: "GUY" },
  { name: "HAITI", iso3: "HTI" },
  { name: "HONDURAS", iso3: "HND" },
  { name: "HONG KONG SAR", iso3: "HKG" },
  { name: "HOWLAND ISLAND", iso3: "XHI" },
  { name: "HUNGARY", iso3: "HUN" },
  { name: "ICELAND", iso3: "ISL" },
  { name: "INDIA", iso3: "IND" },
  { name: "INDONESIA", iso3: "IDN" },
  { name: "IRAN", iso3: "IRN" },
  { name: "IRAQ", iso3: "IRQ" },
  { name: "IRELAND", iso3: "IRL" },
  { name: "ISLE OF MAN", iso3: "IMN" },
  { name: "ISRAEL", iso3: "ISR" },
  { name: "ITALY", iso3: "ITA" },
  { name: "IVORY COAST", iso3: "CIV" },
  { name: "JAMAICA", iso3: "JAM" },
  { name: "JAPAN", iso3: "JPN" },
  { name: "JERSEY", iso3: "JEY" },
  { name: "JERUSALEM", iso3: "XJE" },
  { name: "JOHNSTON ATOLL", iso3: "XJA" },
  { name: "JORDAN", iso3: "JOR" },
  { name: "KAZAKHSTAN", iso3: "KAZ" },
  { name: "KENYA", iso3: "KEN" },
  { name: "KIRIBATI", iso3: "KIR" },
  { name: "KOREA", iso3: "KOR" },
  { name: "KOSOVO", iso3: "KSV" },
  { name: "KUWAIT", iso3: "KWT" },
  { name: "KYRGYZSTAN", iso3: "KGZ" },
  { name: "LAOS", iso3: "LAO" },
  { name: "LATVIA", iso3: "LVA" },
  { name: "LEBANON", iso3: "LBN" },
  { name: "LESOTHO", iso3: "LSO" },
  { name: "LIBERIA", iso3: "LBR" },
  { name: "LIBYA", iso3: "LBY" },
  { name: "LIECHTENSTEIN", iso3: "LIE" },
  { name: "LITHUANIA", iso3: "LTU" },
  { name: "LUXEMBOURG", iso3: "LUX" },
  { name: "MACAU", iso3: "MAC" },
  { name: "MADAGASCAR", iso3: "MDG" },
  { name: "MALAWI", iso3: "MWI" },
  { name: "MALAYSIA", iso3: "MYS" },
  { name: "MALDIVES", iso3: "MDV" },
  { name: "MALI", iso3: "MLI" },
  { name: "MALTA", iso3: "MLT" },
  { name: "MARSHALL ISLANDS", iso3: "MHL" },
  { name: "MARTINIQUE", iso3: "MTQ" },
  { name: "MAURITANIA", iso3: "MRT" },
  { name: "MAURITIUS", iso3: "MUS" },
  { name: "MEXICO", iso3: "MEX" },
  { name: "MICRONESIA", iso3: "FSM" },
  { name: "MIDWAY ISLANDS", iso3: "XMI" },
  { name: "MOLDOVA", iso3: "MDA" },
  { name: "MONACO", iso3: "MCO" },
  { name: "MONGOLIA", iso3: "MNG" },
  { name: "MONTENEGRO", iso3: "MNE" },
  { name: "MONTSERRAT", iso3: "MSR" },
  { name: "MOROCCO", iso3: "MAR" },
  { name: "MOZAMBIQUE", iso3: "MOZ" },
  { name: "NAMIBIA", iso3: "NAM" },
  { name: "NAURU", iso3: "NRU" },
  { name: "NEPAL", iso3: "NPL" },
  { name: "NETHERLANDS", iso3: "NLD" },
  { name: "NEW CALEDONIA", iso3: "NCL" },
  { name: "NEW ZEALAND", iso3: "NZL" },
  { name: "NICARAGUA", iso3: "NIC" },
  { name: "NIGER", iso3: "NER" },
  { name: "NIGERIA", iso3: "NGA" },
  { name: "NIUE", iso3: "NIU" },
  { name: "NORFOLK ISLAND", iso3: "NFK" },
  { name: "NORTH MACEDONIA", iso3: "MKD" },
  { name: "NORTH MARIANA IS., U.S.A.", iso3: "MNP" },
  { name: "NORWAY", iso3: "NOR" },
  { name: "OMAN", iso3: "OMN" },
  { name: "PAKISTAN", iso3: "PAK" },
  { name: "PALAU", iso3: "PLW" },
  { name: "PALESTINE", iso3: "XPL" },
  { name: "PALMYRA ATOLL", iso3: "XPA" },
  { name: "PANAMA", iso3: "PAN" },
  { name: "PAPUA NEW GUINEA", iso3: "PNG" },
  { name: "PARAGUAY", iso3: "PRY" },
  { name: "PERU", iso3: "PER" },
  { name: "PHILIPPINES", iso3: "PHL" },
  { name: "PITCAIRN ISLANDS", iso3: "PCN" },
  { name: "POLAND", iso3: "POL" },
  { name: "PORTUGAL", iso3: "PRT" },
  { name: "PUERTO RICO, U.S.A.", iso3: "PRI" },
  { name: "QATAR", iso3: "QAT" },
  { name: "REUNION", iso3: "REU" },
  { name: "ROMANIA", iso3: "ROM" },
  { name: "RUSSIA", iso3: "RUS" },
  { name: "RWANDA", iso3: "RWA" },
  { name: "SABA", iso3: "SAB" },
  { name: "SAINT MAARTEN", iso3: "STM" },
  { name: "SAMOA", iso3: "WSM" },
  { name: "SAN MARINO", iso3: "SMR" },
  { name: "SAO TOME AND PRINCIPE", iso3: "STP" },
  { name: "SAUDI ARABIA", iso3: "SAU" },
  { name: "SENEGAL", iso3: "SEN" },
  { name: "SERBIA", iso3: "SRM" },
  { name: "SEYCHELLES", iso3: "SYC" },
  { name: "SIERRA LEONE", iso3: "SLE" },
  { name: "SINGAPORE", iso3: "SGP" },
  { name: "SLOVAKIA", iso3: "SVK" },
  { name: "SLOVENIA", iso3: "SVN" },
  { name: "SOLOMON ISLANDS", iso3: "SLB" },
  { name: "SOMALIA", iso3: "SOM" },
  { name: "SOUTH AFRICA", iso3: "ZAF" },
  { name: "SPAIN", iso3: "ESP" },
  { name: "SRI LANKA", iso3: "LKA" },
  { name: "ST. EUSTATIUS", iso3: "STE" },
  { name: "ST. HELENA", iso3: "SHN" },
  { name: "ST. KITTS AND NEVIS", iso3: "KNA" },
  { name: "ST. LUCIA", iso3: "LCA" },
  { name: "ST. MARTIN", iso3: "XSM" },
  { name: "ST. PIERRE AND MIQUELON", iso3: "SPM" },
  { name: "ST. VINCENT, GRENADINES", iso3: "VCT" },
  { name: "SUDAN", iso3: "SDN" },
  { name: "SOUTH SUDAN", iso3: "SSD" },
  { name: "SURINAME", iso3: "SUR" },
  { name: "SWEDEN", iso3: "SWE" },
  { name: "SWITZERLAND", iso3: "CHE" },
  { name: "SYRIA", iso3: "SYR" },
  { name: "TAIWAN", iso3: "TWN" },
  { name: "TAJIKISTAN", iso3: "TJK" },
  { name: "TANZANIA", iso3: "TZA" },
  { name: "THAILAND", iso3: "THA" },
  { name: "THE BAHAMAS", iso3: "BHS" },
  { name: "THE GAMBIA", iso3: "GMB" },
  { name: "TIMOR-LESTE", iso3: "TMR" },
  { name: "TOGO", iso3: "TGO" },
  { name: "TOKELAU", iso3: "TKL" },
  { name: "TONGA", iso3: "TON" },
  { name: "TRINIDAD AND TOBAGO", iso3: "TTO" },
  { name: "TUNISIA", iso3: "TUN" },
  { name: "TURKEY", iso3: "TUR" },
  { name: "TURKMENISTAN", iso3: "TKM" },
  { name: "TURKS AND CAICOS ISLANDS", iso3: "TCA" },
  { name: "TUVALU", iso3: "TUV" },
  { name: "UGANDA", iso3: "UGA" },
  { name: "UKRAINE", iso3: "UKR" },
  { name: "UNITED ARAB EMIRATES", iso3: "ARE" },
  { name: "UNITED KINGDOM", iso3: "GBR" },
  { name: "UNKNOWN", iso3: "XXX" },
  { name: "URUGUAY", iso3: "URY" },
  { name: "U.S. VIRGIN ISLANDS", iso3: "VIR" },
  { name: "UZBEKISTAN", iso3: "UZB" },
  { name: "VANUATU", iso3: "VUT" },
  { name: "VENEZUELA", iso3: "VEN" },
  { name: "VIETNAM", iso3: "VNM" },
  { name: "WAKE ISLAND", iso3: "XWK" },
  { name: "WALLIS AND FUTUNA", iso3: "WLF" },
  { name: "WEST BANK", iso3: "XWB" },
  { name: "WESTERN SAHARA", iso3: "ESH" },
  { name: "YEMEN", iso3: "YEM" },
  { name: "ZAMBIA", iso3: "ZMB" },
  { name: "ZIMBABWE", iso3: "ZWE" },
];

export const MAILING_COUNTRIES = [
  { name: "UNITED STATES", iso3: "USA" },
  { name: "CANADA", iso3: "CAN" },
  { name: "AFGHANISTAN", iso3: "AFG" },
  { name: "ALBANIA", iso3: "ALB" },
  { name: "ALGERIA", iso3: "DZA" },
  { name: "ANDORRA", iso3: "AND" },
  { name: "ANGOLA", iso3: "AGO" },
  { name: "ANGUILLA", iso3: "AIA" },
  { name: "ANTIGUA AND BARBUDA", iso3: "ATG" },
  { name: "ARGENTINA", iso3: "ARG" },
  { name: "ARMENIA", iso3: "ARM" },
  { name: "ARUBA", iso3: "ABW" },
  { name: "AUSTRALIA", iso3: "AUS" },
  { name: "AUSTRIA", iso3: "AUT" },
  { name: "AZERBAIJAN", iso3: "AZE" },
  { name: "BAHRAIN", iso3: "BHR" },
  { name: "BAKER ISLAND", iso3: "XBK" },
  { name: "BANGLADESH", iso3: "BGD" },
  { name: "BARBADOS", iso3: "BRB" },
  { name: "BELARUS", iso3: "BLR" },
  { name: "BELGIUM", iso3: "BEL" },
  { name: "BELIZE", iso3: "BLZ" },
  { name: "BENIN", iso3: "BEN" },
  { name: "BERMUDA", iso3: "BMU" },
  { name: "BHUTAN", iso3: "BTN" },
  { name: "BOLIVIA", iso3: "BOL" },
  { name: "BONAIRE", iso3: "BON" },
  { name: "BOSNIA AND HERZEGOVINA", iso3: "BIH" },
  { name: "BOTSWANA", iso3: "BWA" },
  { name: "BRAZIL", iso3: "BRA" },
  { name: "BRITISH VIRGIN ISLANDS", iso3: "VGB" },
  { name: "BRUNEI", iso3: "BRN" },
  { name: "BULGARIA", iso3: "BGR" },
  { name: "BURKINA FASO", iso3: "BFA" },
  { name: "BURMA", iso3: "MMR" },
  { name: "BURUNDI", iso3: "BDI" },
  { name: "CAMBODIA", iso3: "KHM" },
  { name: "CAMEROON", iso3: "CMR" },
  // { name: "CANADA", iso3: "CAN" },
  { name: "CABO VERDE", iso3: "CPV" },
  { name: "CAYMAN ISLANDS", iso3: "CYM" },
  { name: "CENTRAL AFRICAN REPUBLIC", iso3: "CAF" },
  { name: "CHAD", iso3: "TCD" },
  { name: "CHILE", iso3: "CHL" },
  { name: "CHINA", iso3: "CHN" },
  { name: "CHRISTMAS ISLAND", iso3: "CXR" },
  { name: "COCOS ISLANDS", iso3: "CCK" },
  { name: "COLOMBIA", iso3: "COL" },
  { name: "COMOROS", iso3: "COM" },
  { name: "CONGO-BRAZZAVILLE", iso3: "COG" },
  { name: "CONGO-KINSHASA", iso3: "COD" },
  { name: "COOK ISLANDS", iso3: "COK" },
  { name: "COSTA RICA", iso3: "CRI" },
  { name: "CROATIA", iso3: "HRV" },
  { name: "CUBA", iso3: "CUB" },
  { name: "CURACAO", iso3: "CUR" },
  { name: "CYPRUS", iso3: "CYP" },
  { name: "CZECH REPUBLIC", iso3: "CSK" },
  { name: "DENMARK", iso3: "DNK" },
  { name: "DJIBOUTI", iso3: "DJI" },
  { name: "DOMINICA", iso3: "DMA" },
  { name: "DOMINICAN REPUBLIC", iso3: "DOM" },
  { name: "ECUADOR", iso3: "ECU" },
  { name: "EGYPT", iso3: "EGY" },
  { name: "EL SALVADOR", iso3: "SLV" },
  { name: "EQUATORIAL GUINEA", iso3: "GNQ" },
  { name: "ERITREA", iso3: "ERI" },
  { name: "ESTONIA", iso3: "EST" },
  { name: "ESWATINI", iso3: "SWZ" },
  { name: "ETHIOPIA", iso3: "ETH" },
  { name: "FALKLAND ISLANDS", iso3: "FLK" },
  { name: "FAROE ISLANDS", iso3: "FRO" },
  { name: "FIJI", iso3: "FJI" },
  { name: "FINLAND", iso3: "FIN" },
  { name: "FRANCE", iso3: "FRA" },
  { name: "FRENCH GUIANA", iso3: "GUF" },
  { name: "FRENCH POLYNESIA", iso3: "PYF" },
  { name: "GABON", iso3: "GAB" },
  { name: "GAZA STRIP", iso3: "XGZ" },
  { name: "GEORGIA", iso3: "GEO" },
  { name: "GERMANY", iso3: "DEU" },
  { name: "GHANA", iso3: "GHA" },
  { name: "GIBRALTAR", iso3: "GIB" },
  { name: "GREECE", iso3: "GRC" },
  { name: "GREENLAND", iso3: "GRL" },
  { name: "GRENADA", iso3: "GRD" },
  { name: "GUADELOUPE", iso3: "GLP" },
  { name: "GUATEMALA", iso3: "GTM" },
  { name: "GUINEA", iso3: "GIN" },
  { name: "GUINEA-BISSAU", iso3: "GNB" },
  { name: "GUYANA", iso3: "GUY" },
  { name: "HAITI", iso3: "HTI" },
  { name: "HONDURAS", iso3: "HND" },
  { name: "HONG KONG SAR", iso3: "HKG" },
  { name: "HOWLAND ISLAND", iso3: "XHI" },
  { name: "HUNGARY", iso3: "HUN" },
  { name: "ICELAND", iso3: "ISL" },
  { name: "INDIA", iso3: "IND" },
  { name: "INDONESIA", iso3: "IDN" },
  { name: "IRAN", iso3: "IRN" },
  { name: "IRAQ", iso3: "IRQ" },
  { name: "IRELAND", iso3: "IRL" },
  { name: "ISRAEL", iso3: "ISR" },
  { name: "ITALY", iso3: "ITA" },
  { name: "IVORY COAST", iso3: "CIV" },
  { name: "JAMAICA", iso3: "JAM" },
  { name: "JAPAN", iso3: "JPN" },
  { name: "JERUSALEM", iso3: "XJE" },
  { name: "JOHNSTON ATOLL", iso3: "XJA" },
  { name: "JORDAN", iso3: "JOR" },
  { name: "KAZAKHSTAN", iso3: "KAZ" },
  { name: "KENYA", iso3: "KEN" },
  { name: "KIRIBATI", iso3: "KIR" },
  { name: "KOREA", iso3: "KOR" },
  { name: "KOSOVO", iso3: "KSV" },
  { name: "KUWAIT", iso3: "KWT" },
  { name: "KYRGYZSTAN", iso3: "KGZ" },
  { name: "LAOS", iso3: "LAO" },
  { name: "LATVIA", iso3: "LVA" },
  { name: "LEBANON", iso3: "LBN" },
  { name: "LESOTHO", iso3: "LSO" },
  { name: "LIBERIA", iso3: "LBR" },
  { name: "LIBYA", iso3: "LBY" },
  { name: "LIECHTENSTEIN", iso3: "LIE" },
  { name: "LITHUANIA", iso3: "LTU" },
  { name: "LUXEMBOURG", iso3: "LUX" },
  { name: "MACAU", iso3: "MAC" },
  { name: "MADAGASCAR", iso3: "MDG" },
  { name: "MALAWI", iso3: "MWI" },
  { name: "MALAYSIA", iso3: "MYS" },
  { name: "MALDIVES", iso3: "MDV" },
  { name: "MALI", iso3: "MLI" },
  { name: "MALTA", iso3: "MLT" },
  { name: "MARSHALL ISLANDS", iso3: "MHL" },
  { name: "MARTINIQUE", iso3: "MTQ" },
  { name: "MAURITANIA", iso3: "MRT" },
  { name: "MAURITIUS", iso3: "MUS" },
  { name: "MEXICO", iso3: "MEX" },
  { name: "MICRONESIA", iso3: "FSM" },
  { name: "MIDWAY ISLANDS", iso3: "XMI" },
  { name: "MOLDOVA", iso3: "MDA" },
  { name: "MONACO", iso3: "MCO" },
  { name: "MONGOLIA", iso3: "MNG" },
  { name: "MONTENEGRO", iso3: "MNE" },
  { name: "MONTSERRAT", iso3: "MSR" },
  { name: "MOROCCO", iso3: "MAR" },
  { name: "MOZAMBIQUE", iso3: "MOZ" },
  { name: "NAMIBIA", iso3: "NAM" },
  { name: "NAURU", iso3: "NRU" },
  { name: "NEPAL", iso3: "NPL" },
  { name: "NETHERLANDS", iso3: "NLD" },
  { name: "NEW CALEDONIA", iso3: "NCL" },
  { name: "NEW ZEALAND", iso3: "NZL" },
  { name: "NICARAGUA", iso3: "NIC" },
  { name: "NIGER", iso3: "NER" },
  { name: "NIGERIA", iso3: "NGA" },
  { name: "NIUE", iso3: "NIU" },
  { name: "NORFOLK ISLAND", iso3: "NFK" },
  { name: "NORTH MACEDONIA", iso3: "MKD" },
  { name: "NORWAY", iso3: "NOR" },
  { name: "OMAN", iso3: "OMN" },
  { name: "PAKISTAN", iso3: "PAK" },
  { name: "PALAU", iso3: "PLW" },
  { name: "PALESTINE", iso3: "XPL" },
  { name: "PALMYRA ATOLL", iso3: "XPA" },
  { name: "PANAMA", iso3: "PAN" },
  { name: "PAPUA NEW GUINEA", iso3: "PNG" },
  { name: "PARAGUAY", iso3: "PRY" },
  { name: "PERU", iso3: "PER" },
  { name: "PHILIPPINES", iso3: "PHL" },
  { name: "PITCAIRN ISLANDS", iso3: "PCN" },
  { name: "POLAND", iso3: "POL" },
  { name: "PORTUGAL", iso3: "PRT" },
  { name: "QATAR", iso3: "QAT" },
  { name: "REUNION", iso3: "REU" },
  { name: "ROMANIA", iso3: "ROM" },
  { name: "RUSSIA", iso3: "RUS" },
  { name: "RWANDA", iso3: "RWA" },
  { name: "SABA", iso3: "SAB" },
  { name: "SAINT MAARTEN", iso3: "STM" },
  { name: "SAMOA", iso3: "WSM" },
  { name: "SAN MARINO", iso3: "SMR" },
  { name: "SAO TOME AND PRINCIPE", iso3: "STP" },
  { name: "SAUDI ARABIA", iso3: "SAU" },
  { name: "SENEGAL", iso3: "SEN" },
  { name: "SERBIA", iso3: "SRB" },
  { name: "SEYCHELLES", iso3: "SYC" },
  { name: "SIERRA LEONE", iso3: "SLE" },
  { name: "SINGAPORE", iso3: "SGP" },
  { name: "SLOVAKIA", iso3: "SVK" },
  { name: "SLOVENIA", iso3: "SVN" },
  { name: "SOLOMON ISLANDS", iso3: "SLB" },
  { name: "SOMALIA", iso3: "SOM" },
  { name: "SOUTH AFRICA", iso3: "ZAF" },
  { name: "SPAIN", iso3: "ESP" },
  { name: "SRI LANKA", iso3: "LKA" },
  { name: "ST. EUSTATIUS", iso3: "STE" },
  { name: "ST. HELENA", iso3: "SHN" },
  { name: "ST. KITTS AND NEVIS", iso3: "KNA" },
  { name: "ST. LUCIA", iso3: "LCA" },
  { name: "ST. MARTIN", iso3: "XSM" },
  { name: "ST. PIERRE AND MIQUELON", iso3: "SPM" },
  { name: "ST. VINCENT, GRENADINES", iso3: "VCT" },
  { name: "SUDAN", iso3: "SDN" },
  { name: "SOUTH SUDAN", iso3: "SSD" },
  { name: "SURINAME", iso3: "SUR" },
  { name: "SWEDEN", iso3: "SWE" },
  { name: "SWITZERLAND", iso3: "CHE" },
  { name: "SYRIA", iso3: "SYR" },
  { name: "TAIWAN", iso3: "TWN" },
  { name: "TAJIKISTAN", iso3: "TJK" },
  { name: "TANZANIA", iso3: "TZA" },
  { name: "THAILAND", iso3: "THA" },
  { name: "THE BAHAMAS", iso3: "BHS" },
  { name: "THE GAMBIA", iso3: "GMB" },
  { name: "TIMOR-LESTE", iso3: "TMR" },
  { name: "TOGO", iso3: "TGO" },
  { name: "TOKELAU", iso3: "TKL" },
  { name: "TONGA", iso3: "TON" },
  { name: "TRINIDAD AND TOBAGO", iso3: "TTO" },
  { name: "TUNISIA", iso3: "TUN" },
  { name: "TURKEY", iso3: "TUR" },
  { name: "TURKMENISTAN", iso3: "TKM" },
  { name: "TURKS AND CAICOS ISLANDS", iso3: "TCA" },
  { name: "TUVALU", iso3: "TUV" },
  { name: "UGANDA", iso3: "UGA" },
  { name: "UKRAINE", iso3: "UKR" },
  { name: "UNITED ARAB EMIRATES", iso3: "ARE" },
  { name: "UNITED KINGDOM", iso3: "GBR" },
  // { name: "UNITED STATES", iso3: "USA" },
  { name: "UNKNOWN", iso3: "XXX" },
  { name: "URUGUAY", iso3: "URY" },
  { name: "UZBEKISTAN", iso3: "UZB" },
  { name: "VANUATU", iso3: "VUT" },
  { name: "VENEZUELA", iso3: "VEN" },
  { name: "VIETNAM", iso3: "VNM" },
  { name: "WAKE ISLAND", iso3: "XWK" },
  { name: "WALLIS AND FUTUNA", iso3: "WLF" },
  { name: "WEST BANK", iso3: "XWB" },
  { name: "WESTERN SAHARA", iso3: "ESH" },
  { name: "YEMEN", iso3: "YEM" },
  { name: "ZAMBIA", iso3: "ZMB" },
  { name: "ZIMBABWE", iso3: "ZWE" },
];
